---
# Source: external-secrets/charts/external-secrets/templates/webhook-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-0.19.2
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.19.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/metrics: "webhook"
    external-secrets.io/component: webhook
